Repository Elle624/favo-api, pull requests merged in 2021-01, with the labels that each got.

#5 Fix/open position
  ivolunteerData.js
  server.js
Labels: Express

#6 Fix/user data model
  ivolunteerData.js
  server.js
Labels: Enhancement, Express

#8 Add completed jobs duration to a user
  ivolunteerData.js
Labels: Enhancement
